require 'teneo-data_model'
#noinspection RubyResolve
load Teneo::DataModel::RAKEFILE

require 'teneo-ingester'

path = File.expand_path(__dir__)
#noinspection RubyResolve
Dir.glob(File.join(path, '*.rake')).each { |f| load f }