default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV['DB_POOL']&.to_i || 15 %>

  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT']&.to_i || 5432 %>

  database: <%= ENV['DB_NAME'] || 'ingester' %>

  username: <%= ENV['DB_USER'] || 'teneo' %>
  password: <%= ENV['DB_PASS'] || 'teneo' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
