default: &default
  adapter: postgresql
  encoding: unicode
  pool: 15

  host: localhost
  port: 5432

  username: teneo
  password: teneo

  migrations_paths:
    - <%= Teneo::DataModel.migrations_path %>
    - "db/migrate"

development:
  <<: *default
  database: teneo_dev

test:
  <<: *default
  database: teneo_test

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] || 'teneo' %>
  port: <%= ENV['DATABASE_PORT']&.to_i || 5432 %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
